### ISSUE TITLE
Generate code that imports precompiled MIBs

### ISSUE THREAD

**Issue by jstys** [etingof/pysmi#18]
I'm trying to generate pysnmp compiled MIBs from ASN text files.  The text files import some of the standard MIBs that are shipped precompiled with pysnmp/smi e.g. "SNMPv2-SMI".  I run into issues when running the mibCompiler.compile() method and it looks like it is trying to generate code for the ASN mibs before it loads the precompiled MIBs from the list of borrowers.

Is there a way to get the precompiled MIBs like "SNMPv2-SMI" that live as a .py in my site-packages folder into the symbolTable of the mibCompiler before the code gen process is run on each of the custom text MIBs?  Or does the MibCompiler require that the ASN sources for all dependencies are present?

**Comment by jstys** [comment]
Here is the code I'm using to compile the custom MIBs (much of the code was mirrored from mibdump.py)

```
def compile_custom_mibs(mibcompiler, mibpath, compiled_dir):
    if os.path.exists(compiled_dir):
        shutil.rmtree(compiled_dir, ignore_errors=True)

    os.mkdir(compiled_dir)

    mibSearchers = PySnmpCodeGen.defaultMibPackages
    mibStubs = [x for x in PySnmpCodeGen.baseMibs if x not in PySnmpCodeGen.fakeMibs]
    searchers = [PyFileSearcher(compiled_dir)]

    for mibSearcher in mibSearchers:
        searchers.append(PyPackageSearcher(mibSearcher))

    searchers.append(StubSearcher(*mibStubs))

    custom = ":".join(["file", mibpath])
    mibcompiler.addSources(*getReadersFromUrls(*[custom], **dict(fuzzyMatching=True)))

    precompiled_path = os.path.dirname(mibs.__file__)
    precompiled_reader = FileReader(precompiled_path)
    precompiled_reader.exts = ['.py']
    borrower = PyFileBorrower(precompiled_reader, genTexts=False)

    mibcompiler.addBorrowers(borrower)
    mibcompiler.addSearchers(*searchers)

    mibnames = []
    for filename in os.listdir(mibpath):
        mibnames.append(os.path.splitext(filename)[0])

    mibcompiler.compile(*mibnames)
```

The `precompiled_path` is the directory that the .py/.pyc files that come packaged with pysnmp are located.

**Comment by etingof** [comment]
>  I run into issues when running the mibCompiler.compile() method and it looks like it is trying to generate code for the ASN mibs before it loads the precompiled MIBs from the list of borrowers.

The compiler never loads up the *.py files, it may only produce them.

The way compiler operates is that it parses the MIB you give it plus all its dependencies into AST, then pass that AST into symbol table [pseudo] code generator which basically resolves and builds up all the dependent MIB objects.

Past this step you end up with the AST holding fully resolved MIB obejcts you can pass to regular code generator(s) to produce whatever text you want out of it.

The *borrower* thing can only pull in a substitute end product (e.g. compiled MIB) which could not be produced in a normal way (along the lines explained above) most likely because of a severe parser error. The MIBs being offered for *borrowing* are produced after manually fixing ASN.1 sources of the troubling MIBs and compiling them.

> Is there a way to get the precompiled MIBs like "SNMPv2-SMI" that live as a .py in my site-packages folder into the symbolTable of the mibCompiler before the code gen process is run on each of the custom text MIBs?

All MIBs should end up in the symbolTable before any codegeneration happens. Including *SNMPv2-SMI*. You should be able to see them all being compiled once pysmi debugging is on:

    from pysmi import debug

    debug.setLogger(debug.Debug('all'))

>  Or does the MibCompiler require that the ASN sources for all dependencies are present?

Absolutely, it does! If you point it to the [online MIB repo](http://mibs.snmplabs.com/asn1/), you should get them all resolved automatically.

**Comment by jstys** [comment]
> Absolutely, it does! If you point it to the online MIB repo, you should get them all resolved automatically.
Okay thank you for the clarification, I was a little lost on whether the compiled pysnmp MIBs could completely replace the ASN sources.  Appreciate the library, just started using it and it's already making my life easier.
